import {Record} from 'immutable';

export default Record({
  utilityState: '',
  utilityType: '',
  name: '',
  priceUnit: '',
  pricePerUnit: null,
  flatRate: null,
  priceStructure: '',
  hasCancellationFee: null,
  cancellationFee: '',
  hasMonthlyFee: null,
  monthlyFee: '',
  hasEnrollmentFee: null,
  enrollmentFee: '',
  hasNetMetering: null,
  netMetering: '',
  requiresDeposit: null,
  hasBulkDiscounts: null,
  isIntroductoryPrice: null,
  hasRenewable: null,
  renewablePercentage: null,
  termMonthLength: null,
  supplierPhone: '',
  hasTermEndDate: null,
  termEndDate: null,
  offerId: '',
  offerUrl: '',
});
